Add newer versions of PHP to .travis.yml
pear/HTML_QuickForm2 pull request #2
Opened 2018-12-07 19:34 UTC by paragonie-scott

2018-12-08 19:27 UTC, ashnazg requested changes

2018-12-08 19:27 UTC, ashnazg commented on .travis.yml
> +install: composer install
Composer activity will not work on older php5's, as evidenced by the Travis builds. So it will need to either be removed, or only performed when the PHP version can allow for it.

2018-12-08 19:27 UTC, ashnazg commented on .travis.yml
> -install: pear install HTML_Common2
This install/script method of installing and testing needs to be restored.  This verifies the *PEAR* installation, and presumably the `phpunit` system installation will be of a version that fits with the PHP version that's installed.

2018-12-08 19:27 UTC, ashnazg commented on composer.json
> +        "phpunit/phpunit": "^5"
Drop this back to `*` for now, so that the running PHP version has some control over what version gets installed.

2019-04-06 16:21 UTC, sad-spirit commented
Thanks for the inspiration, I managed to devise .travis.yml that somewhat runs on PHPs from 5.2 to 7.3

5.2 is a major pain in the backside as neither composer nor pear work there (the latter due to lack of openssl support in PHP). 

I also fixed PHPUnit versions in composer.json so that phpunit will run on PHP 7+

2019-04-06 16:21 UTC, closed without merging